-- Crear la tabla para almacenar todos los movimientos unificados
create table public.movimientos_bancarios (
  id bigint generated by default as identity primary key,
  fecha date not null,
  banco text not null,
  concepto_original text,
  concepto_agrupador text not null,
  importe numeric not null,
  tipo text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (opcional, pero buena práctica)
alter table public.movimientos_bancarios enable row level security;

-- Crear política para permitir insertar y leer de forma anónima (al ser interno de la empresa)
create policy "Allow anonymous access"
on public.movimientos_bancarios
for all
to anon
using (true)
with check (true);
